### ISSUE TITLE
AAAA Support

### ISSUE THREAD

**Issue by javiergayala** [greg-hellings/dnszone#2]
Hello,

I am using this module in one of my Python scripts, and I had a need to manipulate AAAA records within the zone file.  I have submitted PR #1 for review which includes support for AAAA records.  Please let me know if you need anything from me!  Thanks!

**Comment by greg-hellings** [comment]
Thanks for the PR!

**Comment by greg-hellings** [comment]
2.0.2 is up on PyPI with your updates: https://pypi.org/project/dnszone/
